
spring:
  application:
    name: account-service

  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
#      username: root            // dùng đi kèm với config server khi config server sử dụng spring security - username and password là user và pass của config server
#      password: root






