spring:
  application:
    name: statistic-service

  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:FREE
#    username: c##cloud
#    password: hieu
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.OracleDialect
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#logging:
#  level:
#    root: info
#server:
#  port: 9082