spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: c##cloud
    password: hieu
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  cloud:
    openfeign:
      client:
        default-config:
          connect-timeout: 5000
          read-timeout: 5000
#          nếu connect tới các client quá thời gian timeout thì circuit breaker sẽ được kích hoạt chặn request tới service đó
      circuitbreaker:
        enabled: true

#         resilience4j bổ trợ cho circuit breaker là khi client quá thời gian timeout nó sẽ connect lại sau 1 thời gian, nếu mà vẫn timeout thì sẽ để circuitbreaker đóng
resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
server:
  port: 9081