springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always