spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: iwillwin2211@gmail.com
    password: wqas iogy ynlo qzuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

server:
  port: 9083